services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx:/etc/nginx/conf.d
        ports:
            - "80:80"
        depends_on:
            - app
        container_name: nginx
        networks:
            - prod-network

    app:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
            - /var/www/vendor
            - /var/www/node_modules
        depends_on:
            - db
            - cache
            - mailpit
        ports:
            - "9000:8000"
        command: >
            sh -c "composer install &&
            npm install &&
            npm run build &&
            php artisan key:generate &&
            php artisan lcc &&
            chmod -R 775 storage &&
            chown -R www-data:www-data storage &&
            php artisan migrate &&
            php artisan db:seed &&
            php artisan storage:link &&
            npm run dev"
        working_dir: /var/www
        container_name: app
        networks:
            - prod-network

    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: SagaOnline
            MYSQL_ROOT_PASSWORD: 438fb17f-d5c6-4078-ac95-018d06c2f91c
        ports:
            - "49153:3306"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        container_name: db
        networks:
            - prod-network

    cache:
        image: redis:latest
        restart: always
        volumes:
            - ./tmp/redis:/data
        ports:
            - "49154:6379"
        container_name: cache
        networks:
            - prod-network

    mailpit:
        image: axllent/mailpit
        ports:
            - "49155:1025"
            - "49156:8025"
        container_name: mailpit
        networks:
            - prod-network

networks:
    prod-network:
        driver: bridge
