name: Docker Compose Test

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - php: '8.2'
            laravel: 11
          - php: '8.3'
            laravel: 11
          - php: '8.4'
            laravel: 11

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist

      - name: Set up Laravel environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Run Migrations
        run: |
          docker-compose exec -T app php artisan migrate --no-interaction

      - name: Run Tests in Docker Container
        run: |
          docker-compose exec -T app ./vendor/bin/phpunit --configuration phpunit.xml --coverage-text

      - name: Stop Docker Containers
        run: |
          docker-compose down
