services:
    app:
        build:
            context: ..
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./storage:/var/www/storage
            - ./bootstrap/cache:/var/www/bootstrap/cache
        ports:
            - '9000:9000'
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: laravel-db
        restart: unless-stopped
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: your-database
            MYSQL_ROOT_PASSWORD: root-password
            MYSQL_USER: your-username
            MYSQL_PASSWORD: your-password
        volumes:
            - dbdata:/var/lib/mysql

    vite:
        image: node:20
        container_name: vite-server
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - '5173:5173'
        command: sh -c "npm install && npm run dev"
        depends_on:
            - app

volumes:
    dbdata:
